### ISSUE TITLE
AttributeError: 'Categorical' object has no attribute 'sort'

### ISSUE THREAD

**Issue by buhtz** [mhowison/codebooks#1]
It seems like that the codebook is not able to handle Categorial data.

https://github.com/mhowison/codebooks/blob/50b6799c4ca46dea6f086722422e5e62401e0539/codebooks/variable.py#L18

The full error is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\IUK\Python\lib\site-packages\codebooks\__init__.py", line 20, in htmlbook
    var = Variable(df[varname], desc.get(varname, ""))
  File "C:\IUK\Python\lib\site-packages\codebooks\variable.py", line 18, in __init__
    self.values.sort()
AttributeError: 'Categorical' object has no attribute 'sort'
```

I would suggest to check if the column is a ordered categorial - then you can sort(). If not, do not sort.

**Comment by buhtz** [comment]
https://github.com/mhowison/codebooks/issues/2

**Comment by mhowison** [comment]
Removed the sort in v0.0.6
