### ISSUE TITLE
FeatureRequest: tqdm

### ISSUE THREAD

**Issue by chae-won-lee** [mhowison/codebooks#7]
Thanks for this codebook Mark!
For large datasets, it would be great to have a progress bar for users to estimate when the report will finish generating. 

I think this would be a one-line change in html.py

from tqdm import tqdm

    for i, varname in tqdm(enumerate(df.columns), total=len(df.columns), desc="Calculating summary rows"):
        var = Variable(
            df[varname],
            desc.get(varname, "")
        )
        var.index = i
        output.append(str(SummaryRow(var)))

**Comment by mhowison** [comment]
Thanks for requesting this @chae-won-lee! It's now implemented in v0.0.6
